#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'CxLppCts'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 2

# The Active Message type associated with this message.
AM_TYPE = 200

class CxLppCts(tinyos.message.Message.Message):
    # Create a new CxLppCts of size 2.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=2):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <CxLppCts> \n"
        try:
            s += "  [addr=0x%x]\n" % (self.get_addr())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: addr
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'addr' is signed (False).
    #
    def isSigned_addr(self):
        return False
    
    #
    # Return whether the field 'addr' is an array (False).
    #
    def isArray_addr(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'addr'
    #
    def offset_addr(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'addr'
    #
    def offsetBits_addr(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'addr'
    #
    def get_addr(self):
        return self.getUIntElement(self.offsetBits_addr(), 16, 1)
    
    #
    # Set the value of the field 'addr'
    #
    def set_addr(self, value):
        self.setUIntElement(self.offsetBits_addr(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'addr'
    #
    def size_addr(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'addr'
    #
    def sizeBits_addr(self):
        return 16
    
