#ifndef AUTO_PUSH_H
#define AUTO_PUSH_H

#ifndef DEFAULT_HIGH_PUSH_THRESHOLD
#define DEFAULT_HIGH_PUSH_THRESHOLD 5
#endif

#ifndef DEFAULT_LOW_PUSH_THRESHOLD
#define DEFAULT_LOW_PUSH_THRESHOLD 2
#endif

#define SS_KEY_LOW_PUSH_THRESHOLD 0x10
#define SS_KEY_HIGH_PUSH_THRESHOLD 0x11

#endif
