#!/bin/bash
if [ $# -lt 1 ]
then
  echo "Usage: $0 <map> [additional make args]"
  exit 1
fi
MAP=$1
shift 1

make bacon2 $@

for i in `cut -d ' ' -f 2 $MAP`
do
  make bacon2 reinstall,$i wpt,$MAP
done
