#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'CxRecordRequestMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 8

# The Active Message type associated with this message.
AM_TYPE = 240

class CxRecordRequestMsg(tinyos.message.Message.Message):
    # Create a new CxRecordRequestMsg of size 8.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=8):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <CxRecordRequestMsg> \n"
        try:
            s += "  [node_id=0x%x]\n" % (self.get_node_id())
        except:
            pass
        try:
            s += "  [cookie=0x%x]\n" % (self.get_cookie())
        except:
            pass
        try:
            s += "  [length=0x%x]\n" % (self.get_length())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: node_id
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'node_id' is signed (False).
    #
    def isSigned_node_id(self):
        return False
    
    #
    # Return whether the field 'node_id' is an array (False).
    #
    def isArray_node_id(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'node_id'
    #
    def offset_node_id(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'node_id'
    #
    def offsetBits_node_id(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'node_id'
    #
    def get_node_id(self):
        return self.getUIntElement(self.offsetBits_node_id(), 16, 1)
    
    #
    # Set the value of the field 'node_id'
    #
    def set_node_id(self, value):
        self.setUIntElement(self.offsetBits_node_id(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'node_id'
    #
    def size_node_id(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'node_id'
    #
    def sizeBits_node_id(self):
        return 16
    
    #
    # Accessor methods for field: cookie
    #   Field type: long
    #   Offset (bits): 16
    #   Size (bits): 32
    #

    #
    # Return whether the field 'cookie' is signed (False).
    #
    def isSigned_cookie(self):
        return False
    
    #
    # Return whether the field 'cookie' is an array (False).
    #
    def isArray_cookie(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'cookie'
    #
    def offset_cookie(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'cookie'
    #
    def offsetBits_cookie(self):
        return 16
    
    #
    # Return the value (as a long) of the field 'cookie'
    #
    def get_cookie(self):
        return self.getUIntElement(self.offsetBits_cookie(), 32, 1)
    
    #
    # Set the value of the field 'cookie'
    #
    def set_cookie(self, value):
        self.setUIntElement(self.offsetBits_cookie(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'cookie'
    #
    def size_cookie(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'cookie'
    #
    def sizeBits_cookie(self):
        return 32
    
    #
    # Accessor methods for field: length
    #   Field type: int
    #   Offset (bits): 48
    #   Size (bits): 16
    #

    #
    # Return whether the field 'length' is signed (False).
    #
    def isSigned_length(self):
        return False
    
    #
    # Return whether the field 'length' is an array (False).
    #
    def isArray_length(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'length'
    #
    def offset_length(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'length'
    #
    def offsetBits_length(self):
        return 48
    
    #
    # Return the value (as a int) of the field 'length'
    #
    def get_length(self):
        return self.getUIntElement(self.offsetBits_length(), 16, 1)
    
    #
    # Set the value of the field 'length'
    #
    def set_length(self, value):
        self.setUIntElement(self.offsetBits_length(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'length'
    #
    def size_length(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'length'
    #
    def sizeBits_length(self):
        return 16
    
