COMPONENT=TestAppC

CFLAGS+=-I$(TOSDIR)/lib/serialprintf
CFLAGS += -I$(TOSDIR)/lib/priorityQueue

CFLAGS += -I$(TOSDIR)/lib/cx/link
CFLAGS += -I$(TOSDIR)/lib/rf1a-tdma/timer

CFLAGS+=-DXT2_SMCLK

include $(MAKERULES)

