
SS_KEY_LOW_PUSH_THRESHOLD=0x10 #(uint8_t)
SS_KEY_HIGH_PUSH_THRESHOLD=0x11 #(uint8_t)
SS_KEY_TOAST_SAMPLE_INTERVAL=0x12 #(uint32_t)
SS_KEY_REBOOT_COUNTER=0x13 #(uint16_t)
SS_KEY_BACON_SAMPLE_INTERVAL=0x14 #(uint32_t)
SS_KEY_PROBE_SCHEDULE=0x15 #(probe_schedule_t) (CXMac.h)
SS_KEY_PHOENIX_SAMPLE_INTERVAL=0x16 #(uint32_t) (phoenix.h)
SS_KEY_PHOENIX_TARGET_REFS=0x17 #(uint32_t) (phoenix.h)
SS_KEY_DOWNLOAD_INTERVAL=0x18   #(uint32_t) (router.h)

NS_GLOBAL=0
NS_SUBNETWORK=1
NS_ROUTER=2
