#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'StatusTimeRef'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 8

# The Active Message type associated with this message.
AM_TYPE = 211

class StatusTimeRef(tinyos.message.Message.Message):
    # Create a new StatusTimeRef of size 8.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=8):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <StatusTimeRef> \n"
        try:
            s += "  [node=0x%x]\n" % (self.get_node())
        except:
            pass
        try:
            s += "  [rc=0x%x]\n" % (self.get_rc())
        except:
            pass
        try:
            s += "  [ts=0x%x]\n" % (self.get_ts())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: node
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'node' is signed (False).
    #
    def isSigned_node(self):
        return False
    
    #
    # Return whether the field 'node' is an array (False).
    #
    def isArray_node(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'node'
    #
    def offset_node(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'node'
    #
    def offsetBits_node(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'node'
    #
    def get_node(self):
        return self.getUIntElement(self.offsetBits_node(), 16, 1)
    
    #
    # Set the value of the field 'node'
    #
    def set_node(self, value):
        self.setUIntElement(self.offsetBits_node(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'node'
    #
    def size_node(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'node'
    #
    def sizeBits_node(self):
        return 16
    
    #
    # Accessor methods for field: rc
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'rc' is signed (False).
    #
    def isSigned_rc(self):
        return False
    
    #
    # Return whether the field 'rc' is an array (False).
    #
    def isArray_rc(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'rc'
    #
    def offset_rc(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'rc'
    #
    def offsetBits_rc(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'rc'
    #
    def get_rc(self):
        return self.getUIntElement(self.offsetBits_rc(), 16, 1)
    
    #
    # Set the value of the field 'rc'
    #
    def set_rc(self, value):
        self.setUIntElement(self.offsetBits_rc(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'rc'
    #
    def size_rc(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'rc'
    #
    def sizeBits_rc(self):
        return 16
    
    #
    # Accessor methods for field: ts
    #   Field type: long
    #   Offset (bits): 32
    #   Size (bits): 32
    #

    #
    # Return whether the field 'ts' is signed (False).
    #
    def isSigned_ts(self):
        return False
    
    #
    # Return whether the field 'ts' is an array (False).
    #
    def isArray_ts(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'ts'
    #
    def offset_ts(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'ts'
    #
    def offsetBits_ts(self):
        return 32
    
    #
    # Return the value (as a long) of the field 'ts'
    #
    def get_ts(self):
        return self.getUIntElement(self.offsetBits_ts(), 32, 1)
    
    #
    # Set the value of the field 'ts'
    #
    def set_ts(self, value):
        self.setUIntElement(self.offsetBits_ts(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'ts'
    #
    def size_ts(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'ts'
    #
    def sizeBits_ts(self):
        return 32
    
