#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'TestPayload'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 14

# The Active Message type associated with this message.
AM_TYPE = 220

class TestPayload(tinyos.message.Message.Message):
    # Create a new TestPayload of size 14.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=14):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <TestPayload> \n"
        try:
            s += "  [body=";
            for i in range(0, 10):
                s += "0x%x " % (self.getElement_body(i) & 0xff)
            s += "]\n";
        except:
            pass
        try:
            s += "  [timestamp=0x%x]\n" % (self.get_timestamp())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: body
    #   Field type: short[]
    #   Offset (bits): 0
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'body' is signed (False).
    #
    def isSigned_body(self):
        return False
    
    #
    # Return whether the field 'body' is an array (True).
    #
    def isArray_body(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'body'
    #
    def offset_body(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 10:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'body'
    #
    def offsetBits_body(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 10:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'body' as a short[]
    #
    def get_body(self):
        tmp = [None]*10
        for index0 in range (0, self.numElements_body(0)):
                tmp[index0] = self.getElement_body(index0)
        return tmp
    
    #
    # Set the contents of the array 'body' from the given short[]
    #
    def set_body(self, value):
        for index0 in range(0, len(value)):
            self.setElement_body(index0, value[index0])

    #
    # Return an element (as a short) of the array 'body'
    #
    def getElement_body(self, index1):
        return self.getUIntElement(self.offsetBits_body(index1), 8, 1)
    
    #
    # Set an element of the array 'body'
    #
    def setElement_body(self, index1, value):
        self.setUIntElement(self.offsetBits_body(index1), 8, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'body'
    #
    def totalSize_body(self):
        return (80 / 8)
    
    #
    # Return the total size, in bits, of the array 'body'
    #
    def totalSizeBits_body(self):
        return 80
    
    #
    # Return the size, in bytes, of each element of the array 'body'
    #
    def elementSize_body(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'body'
    #
    def elementSizeBits_body(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'body'
    #
    def numDimensions_body(self):
        return 1
    
    #
    # Return the number of elements in the array 'body'
    #
    def numElements_body():
        return 10
    
    #
    # Return the number of elements in the array 'body'
    # for the given dimension.
    #
    def numElements_body(self, dimension):
        array_dims = [ 10,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'body' with a String
    #
    def setString_body(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_body(i, ord(s[i]));
         self.setElement_body(l, 0) #null terminate
    
    #
    # Read the array 'body' as a String
    #
    def getString_body(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_body(i) == chr(0):
                break
            carr += self.getElement_body(i)
        return carr
    
    #
    # Accessor methods for field: timestamp
    #   Field type: long
    #   Offset (bits): 80
    #   Size (bits): 32
    #

    #
    # Return whether the field 'timestamp' is signed (False).
    #
    def isSigned_timestamp(self):
        return False
    
    #
    # Return whether the field 'timestamp' is an array (False).
    #
    def isArray_timestamp(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'timestamp'
    #
    def offset_timestamp(self):
        return (80 / 8)
    
    #
    # Return the offset (in bits) of the field 'timestamp'
    #
    def offsetBits_timestamp(self):
        return 80
    
    #
    # Return the value (as a long) of the field 'timestamp'
    #
    def get_timestamp(self):
        return self.getUIntElement(self.offsetBits_timestamp(), 32, 1)
    
    #
    # Set the value of the field 'timestamp'
    #
    def set_timestamp(self, value):
        self.setUIntElement(self.offsetBits_timestamp(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'timestamp'
    #
    def size_timestamp(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'timestamp'
    #
    def sizeBits_timestamp(self):
        return 32
    
