#ifndef STATE_TIMING_DEBUG_H
#define STATE_TIMING_DEBUG_H

#if defined PORT_STATE_TIMING_CAP && defined PIN_STATE_TIMING_CAP 
#define STATE_TIMING_CAP_TOGGLE_PIN TDMA_TOGGLE_PIN(PORT_STATE_TIMING_CAP, PIN_STATE_TIMING_CAP)
#define STATE_TIMING_CAP_CLEAR_PIN TDMA_CLEAR_PIN(PORT_STATE_TIMING_CAP, PIN_STATE_TIMING_CAP)
#define STATE_TIMING_CAP_SET_PIN TDMA_SET_PIN(PORT_STATE_TIMING_CAP, PIN_STATE_TIMING_CAP)
#else 
#define STATE_TIMING_CAP_TOGGLE_PIN 
#define STATE_TIMING_CAP_CLEAR_PIN 
#define STATE_TIMING_CAP_SET_PIN 
#endif

#if defined PORT_STATE_TIMING_TX && defined PIN_STATE_TIMING_TX 
#define STATE_TIMING_TX_TOGGLE_PIN TDMA_TOGGLE_PIN(PORT_STATE_TIMING_TX, PIN_STATE_TIMING_TX)
#define STATE_TIMING_TX_CLEAR_PIN TDMA_CLEAR_PIN(PORT_STATE_TIMING_TX, PIN_STATE_TIMING_TX)
#define STATE_TIMING_TX_SET_PIN TDMA_SET_PIN(PORT_STATE_TIMING_TX, PIN_STATE_TIMING_TX)
#else 
#define STATE_TIMING_TX_TOGGLE_PIN 
#define STATE_TIMING_TX_CLEAR_PIN 
#define STATE_TIMING_TX_SET_PIN 
#endif

#if defined PORT_SW_CAP && defined PIN_SW_CAP 
#define SW_CAP_TOGGLE_PIN TDMA_TOGGLE_PIN(PORT_SW_CAP, PIN_SW_CAP)
#define SW_CAP_CLEAR_PIN TDMA_CLEAR_PIN(PORT_SW_CAP, PIN_SW_CAP)
#define SW_CAP_SET_PIN TDMA_SET_PIN(PORT_SW_CAP, PIN_SW_CAP)
#else 
#define SW_CAP_TOGGLE_PIN 
#define SW_CAP_CLEAR_PIN 
#define SW_CAP_SET_PIN 
#endif

#if defined PORT_SW_OF && defined PIN_SW_OF 
#define SW_OF_TOGGLE_PIN TDMA_TOGGLE_PIN(PORT_SW_OF, PIN_SW_OF)
#define SW_OF_CLEAR_PIN TDMA_CLEAR_PIN(PORT_SW_OF, PIN_SW_OF)
#define SW_OF_SET_PIN TDMA_SET_PIN(PORT_SW_OF, PIN_SW_OF)
#else 
#define SW_OF_TOGGLE_PIN 
#define SW_OF_CLEAR_PIN 
#define SW_OF_SET_PIN 
#endif

#if defined PORT_SW_OFP && defined PIN_SW_OFP 
#define SW_OFP_TOGGLE_PIN TDMA_TOGGLE_PIN(PORT_SW_OFP, PIN_SW_OFP)
#define SW_OFP_CLEAR_PIN TDMA_CLEAR_PIN(PORT_SW_OFP, PIN_SW_OFP)
#define SW_OFP_SET_PIN TDMA_SET_PIN(PORT_SW_OFP, PIN_SW_OFP)
#else 
#define SW_OFP_TOGGLE_PIN 
#define SW_OFP_CLEAR_PIN 
#define SW_OFP_SET_PIN 
#endif

#ifdef DEBUG_SW_CAPTURE
#define printf_SW_CAPTURE(...) printf(__VA_ARGS__)
#else
#define printf_SW_CAPTURE(...) 
#endif



#endif
