#!/bin/bash

./burnRole.sh map.p0 Router\
  MAX_POWER=0x8D\
  GLOBAL_CHANNEL=0\
  SUBNETWORK_CHANNEL=16\
  ROUTER_CHANNEL=64\
  ENABLE_AUTOPUSH=1 
./burnRole.sh map.p0 Leaf -f Makefile.dummycxl \
  MAX_POWER=0x2D\
  GLOBAL_CHANNEL=0\
  SUBNETWORK_CHANNEL=16\
  ROUTER_CHANNEL=64\
  ENABLE_AUTOPUSH=1 

./burnRole.sh map.p1 Router\
  MAX_POWER=0x8D\
  GLOBAL_CHANNEL=0\
  SUBNETWORK_CHANNEL=32\
  ROUTER_CHANNEL=64\
  ENABLE_AUTOPUSH=1 
./burnRole.sh map.p1 Leaf -f Makefile.dummycxl \
  MAX_POWER=0x2D\
  GLOBAL_CHANNEL=0\
  SUBNETWORK_CHANNEL=32\
  ROUTER_CHANNEL=64\
  ENABLE_AUTOPUSH=1 

./burnRole.sh map.p2 Router\
  MAX_POWER=0x8D\
  GLOBAL_CHANNEL=0\
  SUBNETWORK_CHANNEL=48\
  ROUTER_CHANNEL=64\
  ENABLE_AUTOPUSH=1 
./burnRole.sh map.p2 Leaf -f Makefile.dummycxl \
  MAX_POWER=0x2D\
  GLOBAL_CHANNEL=0\
  SUBNETWORK_CHANNEL=48\
  ROUTER_CHANNEL=64\
  ENABLE_AUTOPUSH=1 
