#ifndef CX_TRANSPORT_H
#define CX_TRANSPORT_H

#define CX_TP_SIMPLE_FLOOD 0x01
#define CX_TP_UNRELIABLE_BURST 0x02
#define CX_TP_RELIABLE_BURST 0x03

#ifndef INCLUDE_UNRELIABLE_BURST
#define INCLUDE_UNRELIABLE_BURST 1
#endif

#ifndef INCLUDE_RELIABLE_BURST
#define INCLUDE_RELIABLE_BURST 1
#endif

#endif
