#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'ReadAnalogSensorResponseMsg'
# message type.
#

from tinyos.message.Message import Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 7

# The Active Message type associated with this message.
AM_TYPE = 177

class ReadAnalogSensorResponseMsg(Message):
    # Create a new ReadAnalogSensorResponseMsg of size 7.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=7):
        Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <ReadAnalogSensorResponseMsg> \n"
        try:
            s += "  [sample.inputChannel=0x%x]\n" % (self.get_sample_inputChannel())
        except:
            pass
        try:
            s += "  [sample.sampleTime=0x%x]\n" % (self.get_sample_sampleTime())
        except:
            pass
        try:
            s += "  [sample.sample=0x%x]\n" % (self.get_sample_sample())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: sample.inputChannel
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'sample.inputChannel' is signed (False).
    #
    def isSigned_sample_inputChannel(self):
        return False
    
    #
    # Return whether the field 'sample.inputChannel' is an array (False).
    #
    def isArray_sample_inputChannel(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sample.inputChannel'
    #
    def offset_sample_inputChannel(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'sample.inputChannel'
    #
    def offsetBits_sample_inputChannel(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'sample.inputChannel'
    #
    def get_sample_inputChannel(self):
        return self.getUIntElement(self.offsetBits_sample_inputChannel(), 8, 1)
    
    #
    # Set the value of the field 'sample.inputChannel'
    #
    def set_sample_inputChannel(self, value):
        self.setUIntElement(self.offsetBits_sample_inputChannel(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sample.inputChannel'
    #
    def size_sample_inputChannel(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'sample.inputChannel'
    #
    def sizeBits_sample_inputChannel(self):
        return 8
    
    #
    # Accessor methods for field: sample.sampleTime
    #   Field type: long
    #   Offset (bits): 8
    #   Size (bits): 32
    #

    #
    # Return whether the field 'sample.sampleTime' is signed (False).
    #
    def isSigned_sample_sampleTime(self):
        return False
    
    #
    # Return whether the field 'sample.sampleTime' is an array (False).
    #
    def isArray_sample_sampleTime(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sample.sampleTime'
    #
    def offset_sample_sampleTime(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'sample.sampleTime'
    #
    def offsetBits_sample_sampleTime(self):
        return 8
    
    #
    # Return the value (as a long) of the field 'sample.sampleTime'
    #
    def get_sample_sampleTime(self):
        return self.getUIntElement(self.offsetBits_sample_sampleTime(), 32, 1)
    
    #
    # Set the value of the field 'sample.sampleTime'
    #
    def set_sample_sampleTime(self, value):
        self.setUIntElement(self.offsetBits_sample_sampleTime(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sample.sampleTime'
    #
    def size_sample_sampleTime(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'sample.sampleTime'
    #
    def sizeBits_sample_sampleTime(self):
        return 32
    
    #
    # Accessor methods for field: sample.sample
    #   Field type: int
    #   Offset (bits): 40
    #   Size (bits): 16
    #

    #
    # Return whether the field 'sample.sample' is signed (False).
    #
    def isSigned_sample_sample(self):
        return False
    
    #
    # Return whether the field 'sample.sample' is an array (False).
    #
    def isArray_sample_sample(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sample.sample'
    #
    def offset_sample_sample(self):
        return (40 / 8)
    
    #
    # Return the offset (in bits) of the field 'sample.sample'
    #
    def offsetBits_sample_sample(self):
        return 40
    
    #
    # Return the value (as a int) of the field 'sample.sample'
    #
    def get_sample_sample(self):
        return self.getUIntElement(self.offsetBits_sample_sample(), 16, 1)
    
    #
    # Set the value of the field 'sample.sample'
    #
    def set_sample_sample(self, value):
        self.setUIntElement(self.offsetBits_sample_sample(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sample.sample'
    #
    def size_sample_sample(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'sample.sample'
    #
    def sizeBits_sample_sample(self):
        return 16
    
