#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'ReadBaconSensorResponseMsg'
# message type.
#


from tinyos.message.Message import Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 7

# The Active Message type associated with this message.
AM_TYPE = 179

class ReadBaconSensorResponseMsg(Message):
    # Create a new ReadBaconSensorResponseMsg of size 7.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=7):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <ReadBaconSensorResponseMsg> \n"
        try:
            s += "  [error=0x%x]\n" % (self.get_error())
        except:
            pass
        try:
            s += "  [light=0x%x]\n" % (self.get_light())
        except:
            pass
        try:
            s += "  [thermistor=0x%x]\n" % (self.get_thermistor())
        except:
            pass
        try:
            s += "  [battery=0x%x]\n" % (self.get_battery())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: error
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'error' is signed (False).
    #
    def isSigned_error(self):
        return False
    
    #
    # Return whether the field 'error' is an array (False).
    #
    def isArray_error(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'error'
    #
    def offset_error(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'error'
    #
    def offsetBits_error(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'error'
    #
    def get_error(self):
        return self.getUIntElement(self.offsetBits_error(), 8, 1)
    
    #
    # Set the value of the field 'error'
    #
    def set_error(self, value):
        self.setUIntElement(self.offsetBits_error(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'error'
    #
    def size_error(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'error'
    #
    def sizeBits_error(self):
        return 8
    
    #
    # Accessor methods for field: light
    #   Field type: int
    #   Offset (bits): 8
    #   Size (bits): 16
    #

    #
    # Return whether the field 'light' is signed (False).
    #
    def isSigned_light(self):
        return False
    
    #
    # Return whether the field 'light' is an array (False).
    #
    def isArray_light(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'light'
    #
    def offset_light(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'light'
    #
    def offsetBits_light(self):
        return 8
    
    #
    # Return the value (as a int) of the field 'light'
    #
    def get_light(self):
        return self.getUIntElement(self.offsetBits_light(), 16, 1)
    
    #
    # Set the value of the field 'light'
    #
    def set_light(self, value):
        self.setUIntElement(self.offsetBits_light(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'light'
    #
    def size_light(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'light'
    #
    def sizeBits_light(self):
        return 16
    
    #
    # Accessor methods for field: thermistor
    #   Field type: int
    #   Offset (bits): 24
    #   Size (bits): 16
    #

    #
    # Return whether the field 'thermistor' is signed (False).
    #
    def isSigned_thermistor(self):
        return False
    
    #
    # Return whether the field 'thermistor' is an array (False).
    #
    def isArray_thermistor(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'thermistor'
    #
    def offset_thermistor(self):
        return (24 / 8)
    
    #
    # Return the offset (in bits) of the field 'thermistor'
    #
    def offsetBits_thermistor(self):
        return 24
    
    #
    # Return the value (as a int) of the field 'thermistor'
    #
    def get_thermistor(self):
        return self.getUIntElement(self.offsetBits_thermistor(), 16, 1)
    
    #
    # Set the value of the field 'thermistor'
    #
    def set_thermistor(self, value):
        self.setUIntElement(self.offsetBits_thermistor(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'thermistor'
    #
    def size_thermistor(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'thermistor'
    #
    def sizeBits_thermistor(self):
        return 16
    
    #
    # Accessor methods for field: battery
    #   Field type: int
    #   Offset (bits): 40
    #   Size (bits): 16
    #

    #
    # Return whether the field 'battery' is signed (False).
    #
    def isSigned_battery(self):
        return False
    
    #
    # Return whether the field 'battery' is an array (False).
    #
    def isArray_battery(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'battery'
    #
    def offset_battery(self):
        return (40 / 8)
    
    #
    # Return the offset (in bits) of the field 'battery'
    #
    def offsetBits_battery(self):
        return 40
    
    #
    # Return the value (as a int) of the field 'battery'
    #
    def get_battery(self):
        return self.getUIntElement(self.offsetBits_battery(), 16, 1)
    
    #
    # Set the value of the field 'battery'
    #
    def set_battery(self, value):
        self.setUIntElement(self.offsetBits_battery(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'battery'
    #
    def size_battery(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'battery'
    #
    def sizeBits_battery(self):
        return 16
    
