#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'ReadMfrIdResponseMsg'
# message type.
#

from tinyos.message.Message import Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 9

# The Active Message type associated with this message.
AM_TYPE = 131

class ReadMfrIdResponseMsg(Message):
    # Create a new ReadMfrIdResponseMsg of size 9.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=9):
        Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <ReadMfrIdResponseMsg> \n"
        try:
            s += "  [error=0x%x]\n" % (self.get_error())
        except:
            pass
        try:
            s += "  [mfrId=";
            for i in range(0, 8):
                s += "0x%x " % (self.getElement_mfrId(i) & 0xff)
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: error
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'error' is signed (False).
    #
    def isSigned_error(self):
        return False
    
    #
    # Return whether the field 'error' is an array (False).
    #
    def isArray_error(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'error'
    #
    def offset_error(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'error'
    #
    def offsetBits_error(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'error'
    #
    def get_error(self):
        return self.getUIntElement(self.offsetBits_error(), 8, 1)
    
    #
    # Set the value of the field 'error'
    #
    def set_error(self, value):
        self.setUIntElement(self.offsetBits_error(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'error'
    #
    def size_error(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'error'
    #
    def sizeBits_error(self):
        return 8
    
    #
    # Accessor methods for field: mfrId
    #   Field type: short[]
    #   Offset (bits): 8
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'mfrId' is signed (False).
    #
    def isSigned_mfrId(self):
        return False
    
    #
    # Return whether the field 'mfrId' is an array (True).
    #
    def isArray_mfrId(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'mfrId'
    #
    def offset_mfrId(self, index1):
        offset = 8
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'mfrId'
    #
    def offsetBits_mfrId(self, index1):
        offset = 8
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'mfrId' as a short[]
    #
    def get_mfrId(self):
        tmp = [None]*8
        for index0 in range (0, self.numElements_mfrId(0)):
                tmp[index0] = self.getElement_mfrId(index0)
        return tmp
    
    #
    # Set the contents of the array 'mfrId' from the given short[]
    #
    def set_mfrId(self, value):
        for index0 in range(0, len(value)):
            self.setElement_mfrId(index0, value[index0])

    #
    # Return an element (as a short) of the array 'mfrId'
    #
    def getElement_mfrId(self, index1):
        return self.getUIntElement(self.offsetBits_mfrId(index1), 8, 1)
    
    #
    # Set an element of the array 'mfrId'
    #
    def setElement_mfrId(self, index1, value):
        self.setUIntElement(self.offsetBits_mfrId(index1), 8, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'mfrId'
    #
    def totalSize_mfrId(self):
        return (64 / 8)
    
    #
    # Return the total size, in bits, of the array 'mfrId'
    #
    def totalSizeBits_mfrId(self):
        return 64
    
    #
    # Return the size, in bytes, of each element of the array 'mfrId'
    #
    def elementSize_mfrId(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'mfrId'
    #
    def elementSizeBits_mfrId(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'mfrId'
    #
    def numDimensions_mfrId(self):
        return 1
    
    #
    # Return the number of elements in the array 'mfrId'
    #
    def numElements_mfrId():
        return 8
    
    #
    # Return the number of elements in the array 'mfrId'
    # for the given dimension.
    #
    def numElements_mfrId(self, dimension):
        array_dims = [ 8,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'mfrId' with a String
    #
    def setString_mfrId(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_mfrId(i, ord(s[i]));
         self.setElement_mfrId(l, 0) #null terminate
    
    #
    # Read the array 'mfrId' as a String
    #
    def getString_mfrId(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_mfrId(i) == chr(0):
                break
            carr += self.getElement_mfrId(i)
        return carr
    
