#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'WriteBaconBarcodeIdCmdMsg'
# message type.
#

from tinyos.message.Message import Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 10

# The Active Message type associated with this message.
AM_TYPE = 164

class WriteBaconBarcodeIdCmdMsg(Message):
    # Create a new WriteBaconBarcodeIdCmdMsg of size 10.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=10):
        Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
        #from GlobalId.h
        self.set_tag(0x04)
        self.set_len(8)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <WriteBaconBarcodeIdCmdMsg> \n"
        try:
            s += "  [tag=0x%x]\n" % (self.get_tag())
        except:
            pass
        try:
            s += "  [len=0x%x]\n" % (self.get_len())
        except:
            pass
        try:
            s += "  [barcodeId=";
            for i in range(0, 8):
                s += "0x%x " % (self.getElement_barcodeId(i) & 0xff)
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: tag
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'tag' is signed (False).
    #
    def isSigned_tag(self):
        return False
    
    #
    # Return whether the field 'tag' is an array (False).
    #
    def isArray_tag(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'tag'
    #
    def offset_tag(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'tag'
    #
    def offsetBits_tag(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'tag'
    #
    def get_tag(self):
        return self.getUIntElement(self.offsetBits_tag(), 8, 1)
    
    #
    # Set the value of the field 'tag'
    #
    def set_tag(self, value):
        self.setUIntElement(self.offsetBits_tag(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'tag'
    #
    def size_tag(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'tag'
    #
    def sizeBits_tag(self):
        return 8
    
    #
    # Accessor methods for field: len
    #   Field type: short
    #   Offset (bits): 8
    #   Size (bits): 8
    #

    #
    # Return whether the field 'len' is signed (False).
    #
    def isSigned_len(self):
        return False
    
    #
    # Return whether the field 'len' is an array (False).
    #
    def isArray_len(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'len'
    #
    def offset_len(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'len'
    #
    def offsetBits_len(self):
        return 8
    
    #
    # Return the value (as a short) of the field 'len'
    #
    def get_len(self):
        return self.getUIntElement(self.offsetBits_len(), 8, 1)
    
    #
    # Set the value of the field 'len'
    #
    def set_len(self, value):
        self.setUIntElement(self.offsetBits_len(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'len'
    #
    def size_len(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'len'
    #
    def sizeBits_len(self):
        return 8
    
    #
    # Accessor methods for field: barcodeId
    #   Field type: short[]
    #   Offset (bits): 16
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'barcodeId' is signed (False).
    #
    def isSigned_barcodeId(self):
        return False
    
    #
    # Return whether the field 'barcodeId' is an array (True).
    #
    def isArray_barcodeId(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'barcodeId'
    #
    def offset_barcodeId(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'barcodeId'
    #
    def offsetBits_barcodeId(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 8:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'barcodeId' as a short[]
    #
    def get_barcodeId(self):
        tmp = [None]*8
        for index0 in range (0, self.numElements_barcodeId(0)):
                tmp[index0] = self.getElement_barcodeId(index0)
        return tmp
    
    #
    # Set the contents of the array 'barcodeId' from the given short[]
    #
    def set_barcodeId(self, value):
        for index0 in range(0, len(value)):
            self.setElement_barcodeId(index0, value[index0])

    #
    # Return an element (as a short) of the array 'barcodeId'
    #
    def getElement_barcodeId(self, index1):
        return self.getUIntElement(self.offsetBits_barcodeId(index1), 8, 1)
    
    #
    # Set an element of the array 'barcodeId'
    #
    def setElement_barcodeId(self, index1, value):
        self.setUIntElement(self.offsetBits_barcodeId(index1), 8, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'barcodeId'
    #
    def totalSize_barcodeId(self):
        return (64 / 8)
    
    #
    # Return the total size, in bits, of the array 'barcodeId'
    #
    def totalSizeBits_barcodeId(self):
        return 64
    
    #
    # Return the size, in bytes, of each element of the array 'barcodeId'
    #
    def elementSize_barcodeId(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'barcodeId'
    #
    def elementSizeBits_barcodeId(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'barcodeId'
    #
    def numDimensions_barcodeId(self):
        return 1
    
    #
    # Return the number of elements in the array 'barcodeId'
    #
    def numElements_barcodeId():
        return 8
    
    #
    # Return the number of elements in the array 'barcodeId'
    # for the given dimension.
    #
    def numElements_barcodeId(self, dimension):
        array_dims = [ 8,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'barcodeId' with a String
    #
    def setString_barcodeId(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_barcodeId(i, ord(s[i]));
         self.setElement_barcodeId(l, 0) #null terminate
    
    #
    # Read the array 'barcodeId' as a String
    #
    def getString_barcodeId(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_barcodeId(i) == chr(0):
                break
            carr += self.getElement_barcodeId(i)
        return carr
    
