COMPONENT=TestAppC

#bare-bones printf
CFLAGS+=-I$(TOSDIR)/lib/serialprintf

CFLAGS += -I$(TOSDIR)/chips/msp430/msp430xv2/internalFlash
CFLAGS += -I$(TOSROOT)/apps/breakfast/bacon/settingsStorage
CFLAGS += -I$(TOSDIR)/chips/msp430/tlvStorage

include $(MAKERULES)
