COMPONENT=TestSkewC

CFLAGS+=-I$(TOSDIR)/lib/serialprintf
CFLAGS += -I$(TOSDIR)/lib/cx/packet
CFLAGS += -I$(TOSDIR)/lib/cx/scheduler
CFLAGS += -I$(TOSROOT)/apps/breakfast/util
CFLAGS +=-DCX_ENABLE_SKEW_CORRECTION=1


include $(MAKERULES)

