#!/bin/bash
set -x 
txp=0xC3
floodTest=1
rl=0
rs=0
initSR=100
eos=0x2B00
sp=0

./burn map.nonroot.rx DEBUG_SCALE=3UL TA_DIV=1UL TDMA_ROOT=0 \
  PATABLE0_SETTING=$txp TDMA_INIT_SYMBOLRATE=$initSR DISCONNECTED_SR=500 \
  ENABLE_SKEW_CORRECTION=0 FLOOD_TEST=$floodTest IS_SENDER=0\
  DEBUG_F_STATE=0 DEBUG_SF_STATE=0 DEBUG_AODV_STATE=0\
  DEBUG_F_TESTBED=0 CX_RADIO_LOGGING=$rl DEBUG_RADIO_STATS=$rs\
  END_OF_STACK=$eos STACK_PROTECTION=$sp
./burn map.nonroot.tx DEBUG_SCALE=3UL TA_DIV=1UL TDMA_ROOT=0 \
  PATABLE0_SETTING=$txp TDMA_INIT_SYMBOLRATE=$initSR DISCONNECTED_SR=500 \
  ENABLE_SKEW_CORRECTION=0 FLOOD_TEST=$floodTest IS_SENDER=1\
  DEBUG_F_STATE=0 DEBUG_SF_STATE=0 DEBUG_AODV_STATE=0\
  DEBUG_F_TESTBED=0 CX_RADIO_LOGGING=$rl DEBUG_RADIO_STATS=$rs\
  END_OF_STACK=$eos STACK_PROTECTION=$sp
