#!/bin/bash
txp=0xC3
./burn only_0 DEBUG_SCALE=3UL TA_DIV=1UL TDMA_ROOT=1 \
  TDMA_MAX_DEPTH=10UL TDMA_MAX_NODES=50 \
  PATABLE0_SETTING=$txp TDMA_INIT_SYMBOLRATE=125 \
  DISCONNECTED_SR=500 TDMA_MAX_RETRANSMIT=1UL \
  CX_ADAPTIVE_SR=0 FLOOD_TEST=0
