#!/bin/bash
txp=0xC3
floodTest=0
./burn map.nonroot.rx DEBUG_SCALE=3UL TA_DIV=1UL TDMA_ROOT=0 \
  PATABLE0_SETTING=$txp TDMA_INIT_SYMBOLRATE=125 DISCONNECTED_SR=500 \
  ENABLE_SKEW_CORRECTION=0 FLOOD_TEST=$floodTest IS_SENDER=0
./burn map.nonroot.tx DEBUG_SCALE=3UL TA_DIV=1UL TDMA_ROOT=0 \
  PATABLE0_SETTING=$txp TDMA_INIT_SYMBOLRATE=125 DISCONNECTED_SR=500 \
  ENABLE_SKEW_CORRECTION=0 FLOOD_TEST=$floodTest IS_SENDER=1
